import { ThemeProvider } from '@/components/providers/theme-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from '@/components/providers/auth-provider'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Attendance Tracker App - Tiger\'s Mark Corporation',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: { apple: '/icon.png',},
  themeColor: '#fff',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + " container"}>
        <ThemeProvider attribute='class' defaultTheme='light' enableSystem>
          <AuthProvider>
            <Navbar />
            {children}
            <Footer year='2023' corporation='Brojava'/>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
